/*
SQLyog Community v10.3 
MySQL - 5.5.31 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

## Searches Folder - Import ##
INSERT INTO `SearchFolders` (`FolderID`, `Name`) VALUES(NULL,'Server Management');

## Searches Folder - Get IDs ##
SET @SvrManFolderID = (SELECT `FolderID` FROM `SearchFolders` WHERE `Name` = 'Server Management' ORDER BY `FolderID` DESC LIMIT 1);

## Searches - Import ##
INSERT INTO `SensorChecks` (`SensID`, `Name`, `SQL`, `QueryType`, `ListDATA`, `FolderID`) VALUES(NULL,'Dell OpenManage','Select DISTINCT Computers.ComputerID, Clients.Name as `Client Name`, Computers.Name as ComputerName, Computers.Domain, Computers.UserName, Computers.BiosMFG, Software.`Name` as `Software_Name`, Computers.OS from Computers, Clients, Software Where Computers.ClientID = Clients.ClientID and Software.ComputerID = Computers.ComputerID and (((((Computers.BiosMFG like \'Dell\')) AND (Software.`Name` like \'Dell OpenManage Server Administrator\' OR Software.`Name` = \'Dell OpenManage Array Manager\')) AND (Computers.OS like \'%server%\')) )','4','Manufacturer||Like|Dell|=||=|^Related - Software Installed|Name (Software)|Like|Dell OpenManage Server Administrator|=|Dell OpenManage Array Manager|=|^OS||Like|%server%|=||=|^',@SvrManFolderID);
INSERT INTO `SensorChecks` (`SensID`, `Name`, `SQL`, `QueryType`, `ListDATA`, `FolderID`) VALUES(NULL,'HP Insight','Select DISTINCT Computers.ComputerID, Clients.Name as `Client Name`, Computers.Name as ComputerName, Computers.Domain, Computers.UserName, Computers.BiosMFG, Software.`Name` as `Software_Name` from Computers, Clients, Software Where Computers.ClientID = Clients.ClientID and Software.ComputerID = Computers.ComputerID and ((Computers.BiosMFG like \'Hewlett-Packard\') AND (Software.`Name` in (\'HP Array Configuration Utility (64-bit)\', \'HP Array Configuration Utility\', \'HP Array Configuration Utility CLI\', \'HP Array Diagnostic Utility\', \'HP Array Diagnostics Utility CLI\', \'HP Storage Manager\')))','4','Manufacturer||Like|Hewlett-Packard|=||=|^Related - Software Installed|Name (Software)|Like|HP Array Configuration Utility (64-bit),HP Array Configuration Utility,HP Array Configuration Utility CLI,HP Array Diagnostic Utility,HP Array Diagnostics Utility CLI,HP Storage Manager|=||=|^',@SvrManFolderID);

## Searches = Get IDs ##
SET @DellSrchID = (SELECT `SensID` FROM `SensorChecks` WHERE `Name` = 'Dell OpenManage' ORDER BY `SensID` DESC LIMIT 1);
SET @HpSrchID = (SELECT `SensID` FROM `SensorChecks` WHERE `Name` = 'HP Insight' ORDER BY `SensID` DESC LIMIT 1);

## Groups - Import##
INSERT INTO `MasterGroups` (`GroupID`, `ParentID`, `Parents`, `Children`, `depth`, `Name`, `FullName`, `Permissions`, `Template`, `AutoJoinScript`, `Master`, `LimitToParent`, `Control`, `ControlID`, `Notes`, `MaintenanceID`, `MaintWindowApplied`, `GroupType`, `Priority`, `GUID`) VALUES(NULL,'0',',',',1735,1733,','0','Server Managers','Server Managers','0','0','0','0','0','0','0','','0','0000-00-00 00:00:00','0','5','569f32da-691d-11e4-b192-005056a90f3d');
INSERT INTO `MasterGroups` (`GroupID`, `ParentID`, `Parents`, `Children`, `depth`, `Name`, `FullName`, `Permissions`, `Template`, `AutoJoinScript`, `Master`, `LimitToParent`, `Control`, `ControlID`, `Notes`, `MaintenanceID`, `MaintWindowApplied`, `GroupType`, `Priority`, `GUID`) VALUES(NULL,'1736',',1736,',',','1','Dell OpenManage','Server Managers.Dell OpenManage','0','0',@DellSrchID,'0','1','0','0','','0','2014-11-10 08:29:31','7','5','13fcf208-4c85-11e3-bf79-e4115bb071ca');
INSERT INTO `MasterGroups` (`GroupID`, `ParentID`, `Parents`, `Children`, `depth`, `Name`, `FullName`, `Permissions`, `Template`, `AutoJoinScript`, `Master`, `LimitToParent`, `Control`, `ControlID`, `Notes`, `MaintenanceID`, `MaintWindowApplied`, `GroupType`, `Priority`, `GUID`) VALUES(NULL,'1736',',1736,',',','1','HP Insight Manager','Server Managers.HP Insight Manager','0','0',@HpSrchID,'0','0','0','0','','0','2014-11-10 13:04:56','7','5','fb7e7ac6-4c84-11e3-bf79-e4115bb071ca');

## Groups - Get IDs ##
SET @ServerManagerGrpId = (SELECT `GroupID` FROM `MasterGroups` WHERE `Name` = 'Server Managers' ORDER BY `GroupID` DESC LIMIT 1);
SET @DellGrpID = (SELECT `GroupID` FROM `MasterGroups` WHERE `Name` = 'Dell OpenManage' ORDER BY `GroupID` DESC LIMIT 1);
SET @HpGrpID = (SELECT `GroupID` FROM `MasterGroups` WHERE `Name` = 'HP Insight Manager' ORDER BY `GroupID` DESC LIMIT 1);

## Groups - Update Parent and Child Values ##
UPDATE `MasterGroups` SET `Children` = CONCAT(',', @DellGrpID, ',', @HpGrpID, ',') WHERE `GroupID` = @ServerManagerGrpId;
UPDATE `MasterGroups` SET `Parents` = CONCAT(',', @ServerManagerGrpId, ',') WHERE `GroupID` = @DellGrpID;
UPDATE `MasterGroups` SET `Parents` = CONCAT(',', @ServerManagerGrpId, ',') WHERE `GroupID` = @HpGrpID;
UPDATE `MasterGroups` SET `ParentID` = @ServerManagerGrpId WHERE `GroupID` = @DellGrpID;
UPDATE `MasterGroups` SET `ParentID` = @ServerManagerGrpId WHERE `GroupID` = @HpGrpID;

## Group Monitors - Import ##
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Global Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10893.1.20.110.13.0','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System EventLog Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.41.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Cooling Device Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.21.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Chassis Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.4.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Voltage Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.12.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Temperature Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.24.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Memory Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.27.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - System Chassis Intrusion Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.30.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@DellGrpID,'0','SNMP - Dell OM - Storage System Global Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Unknown, 3-Okay, 4-NonCritical, 5-Critical, 6-NonRecoverable]','0','300','127.0.0.1','6','public1.3.6.1.4.1.674.10892.1.200.10.1.12.1','1','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array Control Board Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.2.2.1.1.10.2','1','2','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array System Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Failed, 4-PredictiveFailure, 5-Erasing, 6-ErasingDone, 7-EraseQueued]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Failed, 4-PredictiveFailure, 5-Erasing, 6-ErasingDone, 7-EraseQueued]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.1.3.0','1','2','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array Accelerator Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.2.2.2.1.2','1','2','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array Smart Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.2.5.1.1.57','1','2','','0','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - System Temperature Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.6.2.6.3.0','4','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - System CPU Fan Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.6.2.6.5.0','4','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - System Fan Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.1.4.0','4','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - System Power Supply Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-NoError, 2-GeneralFailure, 3-BistFailure, 4-FanFailure, 5-TempFailure, 6-InterLockOpen, 7-EpromFailed, 8-VRefFailed, 9-DacFailed, 10-RamTestFailed, 11-VoltageChannelFailed, 12-OrringDiodeFailed, 13-BrownOut, 14-GivenUpOnStartup, 15-NVRam-Invalid, 16-CalibrationTableInvalid]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-NoError, 2-GeneralFailure, 3-BistFailure, 4-FanFailure, 5-TempFailure, 6-InterLockOpen, 7-EpromFailed, 8-VRefFailed, 9-DacFailed, 10-RamTestFailed, 11-VoltageChannelFailed, 12-OrringDiodeFailed, 13-BrownOut, 14-GivenUpOnStartup, 15-NVRam-Invalid, 16-CalibrationTableInvalid]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.6.2.9.3.1.5','1','1','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - System Correctable Memory Errors','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [ [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  [Value Legend: 1-Other, 2-Okay, 3-Degraded, 4-Failed]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.6.2.14.11.1.5','4','3','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array Spare Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. When everything running normally, this spare should be in a \'inactive\' staus. [Value Legend: 1-Other, 2-Invalid, 3-Failed, 4-Inactive, 5-Building, 6-Active]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  When everything running normally, this spare should be in a \'inactive\' staus. [Value Legend: 1-Other, 2-Invalid, 3-Failed, 4-Inactive, 5-Building, 6-Active]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.2.4.1.1.3','7','1,2,4','','1','0','','9','0');
INSERT INTO `groupagents` (`AgentID`, `GroupID`, `SearchID`, `Name`, `CheckAction`, `AlertAction`, `AlertMessage`, `ContactID`, `interval`, `Where`, `What`, `DataOut`, `Comparor`, `DataIn`, `IDField`, `AlertStyle`, `ScriptID`, `DataCollector`, `Category`, `TicketCategory`) VALUES(NULL,@HpGrpID,'0','SNMP - HP IM - Drive Array Logical Drive Status','4','1','%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%.  [Value Legend: 1-Other, 2-Ok, 3-Failed, 4-Unconfigured, 5-Recoverying, 6-ReadyRebuild, 7-Rebuilding, 8-WrongDrive, 9-BadConnect, 10-Overheating, 11-Shutdown, 12-Expanding, 13-NotAvailable, 14-QueuedForExpansion]!!!%Name% %Status% for %ClientName%\\%ComputerName%(%ComputerID%)~~~%Name% %Status% for %ComputerName%(%ComputerID%) at %LocationName% of %ClientName%. The results is %Result%. [Value Legend: 1-Other, 2-Ok, 3-Failed, 4-Unconfigured, 5-Recoverying, 6-ReadyRebuild, 7-Rebuilding, 8-WrongDrive, 9-BadConnect, 10-Overheating, 11-Shutdown, 12-Expanding, 13-NotAvailable, 14-QueuedForExpansion]','0','300','127.0.0.1','6','public1.3.6.1.4.1.232.3.2.5.1.1.6','1','2','','1','0','','9','0');

## Script Folders - Create Store Proc ##
DELIMITER $$
DROP PROCEDURE IF EXISTS `tmpScriptFolderCheckProc`$$
CREATE PROCEDURE tmpScriptFolderCheckProc()
BEGIN
    DECLARE DeviceMonScrptFldrID INT(20);
    DECLARE DeviceMonFunScrptFldrID INT(20);
    SET DeviceMonScrptFldrID = (SELECT `FolderID` FROM `ScriptFolders` WHERE `Name` = 'Device Monitoring' ORDER BY `FolderID` DESC LIMIT 1);
        IF DeviceMonScrptFldrID IS NULL THEN 
        INSERT INTO `scriptfolders` (`FolderID`, `ParentID`, `Name`) VALUES(NULL,'0','Device Monitoring');
    END IF;
    SET DeviceMonScrptFldrID = (SELECT `FolderID` FROM `ScriptFolders` WHERE `Name` = 'Device Monitoring' ORDER BY `FolderID` DESC LIMIT 1);

    SET DeviceMonFunScrptFldrID = (SELECT `FolderID` FROM `ScriptFolders` WHERE `Name` = 'Functions' AND `ParentID` = DeviceMonScrptFldrID ORDER BY `FolderID` DESC LIMIT 1);
    IF DeviceMonFunScrptFldrID IS NULL THEN 
        INSERT INTO `scriptfolders` (`FolderID`, `ParentID`, `Name`) VALUES(NULL,DeviceMonScrptFldrID,'Functions');
    END IF;
END$$
DELIMITER ;

## Script Folders - Call then Drop Store Proc ##
CALL tmpScriptFolderCheckProc();
SET @DeviceMonScrptFldrID = (SELECT `FolderID` FROM `ScriptFolders` WHERE `Name` = 'Device Monitoring' ORDER BY `FolderID` DESC LIMIT 1);
SET @DeviceMonFunScrptFldrID = (SELECT `FolderID` FROM `ScriptFolders` WHERE `Name` = 'Functions' AND `ParentID` = @DeviceMonScrptFldrID ORDER BY `FolderID` DESC LIMIT 1);
DROP PROCEDURE IF EXISTS `tmpScriptFolderCheckProc`;

## Scripts - Import ##
INSERT INTO `lt_scripts` (`ScriptId`, `FolderId`, `ScriptName`, `ScriptNotes`, `Permission`, `EditPermission`, `ComputerScript`, `LocationScript`, `MaintenanceScript`, `FunctionScript`, `LicenseData`, `ScriptData`, `ScriptVersion`, `ScriptGuid`, `ScriptFlags`, `Parameters`, `Last_User`, `Last_Date`) VALUES(NULL,@DeviceMonFunScrptFldrID,'SNMP Service Setup','This script will create the SNMP service and assign the public community string.','0,','0,','1','0','0','0','H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Ih4/L6b5ssmfZm129PjN9So/2n18l38+frVenlTrZZvXRzuP73p/PT59typqvJMfPauLWXY9Sl9Ul/liktfp7v1Rurezey89eHT/4aP93fTlF4/vei88fj2ti1X7k3ndFNUSkMMP9PvP18XsaPZwdv/T/OHB9n5+L9ve3c3vbU/OHzzczvd3d+9PJjsPdqeZeZ9feHzXH89vnPw/0/Mqfd8AAAA=','H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Ih6/ntbFqn2atdnRb5ykqf7d8B/05+m7ts7w7bMiL2dNetd88TKrs0Xe5rX32edlNclK7wMB9pPUqKiWR7uP74YfBK0+Xxezo9nD2f1P84cH2/v5vWx7dze/tz05f/BwO9/f3b0/mew82J1mBgq/wDjrB40/gtdtvrKjOJ62ioD+pp8/Wy/577MZvvP+8ge52xn0Xufve52/9zt/3/foUdXt0Q7hi5/62Um1bIvlOsfn9nf97svmebEo+BXzq35ztpzlyzbjwdC3/p8+SRwVNpBlbxNZ7j0cJszRo5N5Pn3bPL6rf//8JdPuBv45+vbvdfr7/P7Pvzw5fv77f3F88u2zF6e/7+vf5/Wb0y9+35N1XRNGGFBdla/z9vd9ndeXxTRvft/XL754+fs6Kft9fzIri9lJtVisl0Vb5M2j1XpSFtM47cHO+tvGOTh6RF2fFxfrOv/90aG+tb9xZna/6ZnZ/Vmcmb1N/PtmnqdTJel12rR1sbxIiyZt8jZtq/R3r/OLgj69rvNmXba/+/hnhdH3/j9Fzp17G+i59XnebjfCwen2klg3/Rhs9fGd8WvCZv2zoynuDRBw9/+NBHyws4F+v/uquiJZn+dlqSw3IN57cfE+erVeLomH9dt7IRmPHgnKv//r9ZQ0DE/GjcK+//8l4u7uPthA3denz09P3kDgV2tSqcUsPa+rhf27Sb/77dNXp+nWiflg/KzMLpr0F2aL1WG6u7O3f+cz/Jtmy1nqGn35On3x5Zv0+dnvdZp+/LuD+/P6d/+YG7muPvvd3e/vO6mRV3sz+yqfVFX7Is9n+exW83r//1PzeoMXErNh36yO+fSbVtI/q97I3qcbyNW0Wd2md6/Satrk7XqVgmjp3V+0Lsjq3V1WpHnQ4meFjA++aTL+bHLdRtfhd79ZS38grQ7+P0WrTYr327/X8y++AY/3993o8e4PaE+jVTsq8wbiP/z/EvE/IPr4unPxjUUf6nz//q/Z+f79n2VFeSv7tbvz/6kZ2qhLHr2GwmXj9fvrDPysaBQEqf8fotlmo//Dotk3Hp793Fn+JRn4pq3E4gu1vmlqDcViX5taP5sc9nNs4HeHYqv/VxLrNqwFx/Jnj7eGQpb/V5Lr55q3bhmw/L+DWPc3sFZnoB9MmP9PhSC7u5vSbcOiNpDqucEfu4l0B/+fIt0NLpfnOPhe5zcshv9vjyPey+OKsdQ3S6+9b9yr/9n0tjZyGGdVaC0hX2aTMp+lyAe2A+sNq7pa5XV5jYWHn6VFhv9vuf6bKPsNG4S9b9zB/1mlzE2Z0OF4OspQX59s37in/3MmqaARCSgt+PG6X0xG6TtJeIzTV+y1pdU5t8zaNl+s2vQqa35Yy4X/H4safoiS/P+pAOEmY/tD8U/2vvEw4edMiqNr+RBL37imk7VIeMMI8PdrNtAs/hzA4ms23rqQ/bMkxv/fikN+mGL8/60wY7MYy7rs7x8szH7DjPRBIUaMXD+HIky+8CKbzotlns5JNLO0Zvqlq3w5gzzDiZ5myyV9NM8u856sOmEvliTNJez6mlimpJZZC1d7WuZZnc9+doT63s7/l1h3f1NC73eflgV1W8wG8lPUoFqs1rQ4tKQ1ItOou/jW0lry74l/xtQ6vhB39FLnVkQlfU0J6hVNGy1HrVdws3h+wxT/fjgLMcYxHKMMBMaZ5NNs3eTiumV9RW84a5I77jF8cj+c5//fRFPftPK+93MRTZm/n2ZtdvQbJ/8PiTLQNNQsAAA=','1','d9d56e98-4e3a-11e3-bf79-e4115bb071ca','0','','root@localhost','2014-11-10 08:00:00');


